export default{
    name:'testemonials',
    type:'document',
        title:'Testemonials',
    fields:[
        {
            name:'name',
            title:'Name',
            type:'string'
        },
        {
            name:'company',
            title:'Company',
            type:'string'
        },
        {
            name:'imageURL',
            title:'ImageURL',
            type:'image',
            options:{
                hotspot:true,
            }
        },
        {
            name:'feedback',
            title:'Feedback',
            type:'string'
        },
    ]
};